name: cryengine
version: "5.6.0"
summary: Game engine.
description: CRYENGINE is a powerful real-time game development platform created by Crytek.
  
confinement: devmode
base: core18

architectures:
  - build-on: amd64

apps:
  unrealengine:
    command: bin/desktop-launch $SNAP/bin/cryengine
    plugs:
      - home
      - network
      - removable-media
      - opengl
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"
      "DISABLE_WAYLAND": "1"

parts:
  cryengine:
    after: [desktop-glib-only]
    plugin: autotools
    source-type: git
    source: https://github.com/CRYTEK/CRYENGINE.git

   build-packages:
      - g++
      - make
      - build-essential 
      - cmake 
      - dos2unix 
      - clang-3.8 
      - mono-mcs mono-devel 
      - mono-xbuild mono-dmcs 
      - mono-reference-assemblies-4.0 
      - libmono-system-data-datasetextensions4.0-cil 
      - libmono-system-web-extensions4.0-cil 
      - libmono-system-management4.0-cil 
      - libmono-system-xml-linq4.0-cil 
      - libfreetype6-dev
      - libgtk-3-dev 
      - libmono-microsoft-build-tasks-v4.0-4.0-cil 
      - xdg-user-dirs
      - libsdl1.2-dev
      - libpng-dev
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev
    stage-packages:
      - libsdl-sound1.2
      - libsdl-net1.2
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libopenal1
      - libsndio6.1
      - libspeex1
      - libvorbisfile3
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libxkbcommon0
      - libglu1-mesa
      - libasound2
      - libasyncns0
      - libbsd0
      - libcaca0
      - libdbus-1-3
      - libflac8
      - libgcc1
      - libgcrypt20
      - libgl1
      - libglvnd0
      - libglx0
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libncursesw5
      - libogg0
      - libpng16-16
      - libpulse0
      - libsdl1.2debian
      - libslang2
      - libsndfile1
      - libstdc++6
      - libsystemd0
      - libtinfo5
      - libvorbis0a
      - libvorbisenc2
      - libwrap0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - zlib1g
